authors = ["Rune B"]
description = "A muted and pleasant dark theme for Zed with some italics to distinguish certain parts of the syntax. Designed for use with the programming font Victor Mono."
id = "ultimate-dark-neo"
name = "Ultimate Dark Neo"
repository = "https://github.com/rubjo/ultimate-dark-neo-zed"
schema_version = 1
version = "0.0.6"
